### ISSUE TITLE
Add cart queueing indicator to shopping list

### ISSUE THREAD

**Issue by lortza** [lortza/food_planner#244]
Shopping for food is weird right now and out lists are disorganized. I move things from the grocery list to an HEB cart. Mike outs things on an Insta cart order but leaves them on the list. It is hard to know at a glance if something has been added to a cart or simply forgotten. Conversely it is easy to double order. It's messy.

I'd like to add icons for HEB and Insta cart. Perhaps separate them into sections below the regular section. Still need to brainstorm this.

- [x] add new `status` column #246
    - [x] add column
    - [x] populate data
    - [x] add not null constraint
    - [x] update factories and seeds
- [x] display new status in shopping list show #248
    - [x] model validations & specs
    - [x] javascript & styles
    - [x] shopping list item builder logic updates
    - [x] test adding items to list in bulk
    - [x] model status setter methods
    - [x] refactor shopping_list_items_controller
- [x] refactor, debug, finish specs #252
    - [x] resolve bug where "in cart" is being overwritten when added back to the list
    - [x] remove `purchased` from codebase in all the places
    - [x] remove status tag style when crossed off
    - [x] add incoming qty to list items even if they're on the list
    - [x] refactor ShoppingListItemBuilder & controllers to consolidate logic
    - [x] build out shopping_list_item_spec `xit`s
    - [x] build out ShoppingListItemBuilder `xit`s
- [x] remove `purchased` column #253
    - [x] migration to:  `remove_column :table_name, :column_name`

**Comment by lortza** [comment]
Google material icons
```
<span class="material-icons">
add_shopping_cart
</span>

<span class="material-icons">
shopping_cart
</span>
```

https://material.io/resources/icons/?search=cart&icon=shopping_cart&style=baseline

http://google.github.io/material-design-icons/
